### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by djpremier** [prsyahmi/v380#1]
Hi, I have some V380 (macrovideo) cameras and I want to be able to modify her firmware. How are you getting this information to build the program?
If you need collaboration I am available so as soon as possible I will work on porting your code to Python so that I can integrate with Home Assistant (https://home-assistant.io) for example.
Thanks.

**Comment by prsyahmi** [comment]
hi @djpremier,
I use wireshark to capture the packet and replay it with this software. The majority of the packet structure is not reversed yet except the authentication part. The auth part I got from
https://github.com/brusdev/V380-SDK
