### ISSUE TITLE
Connection is being made but no video

### ISSUE THREAD

**Issue by zLupa** [prsyahmi/v380#19]
Hello!

I'm using the v380 (C++) the connection is made but no video is being played by ffplay.
The video seems to be sending because the data is very similar to the data being sended when using the v380 pro android app.

I tried the nodejs implementation but it says that the password is invalid.

Also, if anyone find the problem that is happening and got the video playing, the video is kinda dark because the camera is in a place totally dark.

Wireshark dump: https://anonfiles.com/11n7K2V0xc/v380_video_dump_pcapng
![image](https://user-images.githubusercontent.com/56929033/162803641-754197d1-b58c-48b7-80ef-e6a9991e21f6.png)

**Comment by zalnaRs** [comment]
Hi! Did you fix it?
