### ISSUE TITLE
[Question] Connecting to the camera using the CPP app or a network stream viewer?

### ISSUE THREAD

**Issue by shreyasnagare** [prsyahmi/v380#8]
I have tried both the CPP and the NodeJS versions of your tool. While everything works well on the NodeJS app, I keep getting the following error on the CPP version of the app.
`Unable to find camera with specified mac/id` (Yes, with the same details)
Any idea about why this might be happening?

Have you ever tried using [a basic IP cam viewer](https://play.google.com/store/apps/details?id=com.rcreations.ipcamviewerBasic&hl=en)? Unlike your app, they ask for other details apart from IP and login details like channel number and RTSP port. I'm trying to get the live stream locally on a custom (and older) Android device which doesn't support the official V380 apps. Even to watch a simple network stream, I'd need a URL with protocol, IP, port, login (and possible path/channel) details in it.

**Comment by prsyahmi** [comment]
@shreyasnagare Try supply the ip address eg, `-addr 192.168.1.111`
If the IP isn't given, it will try to discover with broadcast packet. This won't work sometimes.

My v380 camera does not have RTSP protocol with it. The app you are pointing probably works with RTSP. You might want to check if your device has RTSP support. Try using nmap

**Comment by shreyasnagare** [comment]
@shreyasnagare Turns out my v380 didn't support RTSP either. I flashed a v380 `ceshi.ini` file to enable it. Thanks!
